import sqlite3, time
import pandas as pd


tiny_bd = sqlite3.connect('nyc_yellow_tiny.db')
tdata = pd.read_csv(r"D:\lab_bd\nyc_yellow_tiny.csv")
tdata.to_sql('trips', tiny_bd, if_exists='replace', index=False)
cursor = tiny_bd.cursor()
sum1, sum2, sum3, sum4 = 0, 0, 0, 0
for i in range(10):
    t0 = time.perf_counter()
    cursor.execute('SELECT VendorID, count(*) FROM trips GROUP BY 1;')
    res1 = cursor.fetchall()
    t1 = time.perf_counter()
    sum1 += (t1 - t0)
    t0 = time.perf_counter()
    cursor.execute('SELECT passenger_count, avg(total_amount) FROM trips GROUP BY 1;')
    res2 = cursor.fetchall()
    t1 = time.perf_counter()
    sum2 += (t1 - t0)
    t0 = time.perf_counter()
    cursor.execute('''SELECT passenger_count, strftime('%Y', tpep_pickup_datetime), count(*) FROM trips GROUP BY 1, 2;''')
    res3 = cursor.fetchall()
    t1 = time.perf_counter()
    sum3 += (t1 - t0)
    t0 = time.perf_counter()
    cursor.execute('''SELECT passenger_count, strftime('%Y', tpep_pickup_datetime), round(trip_distance), count(*) FROM trips GROUP BY 1, 2, 3 ORDER BY 2, 4 desc;''')
    res4 = cursor.fetchall()
    t1 = time.perf_counter()
    sum4 += (t1 - t0)
    if i == 9:
        print("Query 1")
        print("Result: ", res1)
        print("Elapsed time: ", sum1 / 10)
        print()
        print("Query 2")
        print("Result: ", res2)
        print("Elapsed time: ", sum2 / 10)
        print()
        print("Query 3")
        print("Result: ", res3)
        print("Elapsed time: ", sum3 / 10)
        print()
        print("Query 4")
        print("Result: ", res4)
        print("Elapsed time: ", sum4 / 10)
        print()
cursor.close()
tiny_bd.close()
